apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-c-b-io
  namespace: kube-system
spec:
  secretName: wildcard-c-b-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.c-b.io"
